/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as Lesson9RouteImport } from './routes/lesson9'
import { Route as Lesson8RouteImport } from './routes/lesson8'
import { Route as Lesson7RouteImport } from './routes/lesson7'
import { Route as Lesson6RouteImport } from './routes/lesson6'
import { Route as Lesson5RouteImport } from './routes/lesson5'
import { Route as Lesson4RouteImport } from './routes/lesson4'
import { Route as Lesson3RouteImport } from './routes/lesson3'
import { Route as Lesson25RouteImport } from './routes/lesson25'
import { Route as Lesson24RouteImport } from './routes/lesson24'
import { Route as Lesson23RouteImport } from './routes/lesson23'
import { Route as Lesson22RouteImport } from './routes/lesson22'
import { Route as Lesson21RouteImport } from './routes/lesson21'
import { Route as Lesson20RouteImport } from './routes/lesson20'
import { Route as Lesson19RouteImport } from './routes/lesson19'
import { Route as Lesson11RouteImport } from './routes/lesson11'
import { Route as Lesson10RouteImport } from './routes/lesson10'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChaptersIndexRouteImport } from './routes/chapters.index'
import { Route as LessonLessonIdRouteImport } from './routes/lesson.$lessonId'
import { Route as ChaptersChapterIdRouteImport } from './routes/chapters.$chapterId'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const Lesson9Route = Lesson9RouteImport.update({
  id: '/lesson9',
  path: '/lesson9',
  getParentRoute: () => rootRouteImport,
} as any)
const Lesson8Route = Lesson8RouteImport.update({
  id: '/lesson8',
  path: '/lesson8',
  getParentRoute: () => rootRouteImport,
} as any)
const Lesson7Route = Lesson7RouteImport.update({
  id: '/lesson7',
  path: '/lesson7',
  getParentRoute: () => rootRouteImport,
} as any)
const Lesson6Route = Lesson6RouteImport.update({
  id: '/lesson6',
  path: '/lesson6',
  getParentRoute: () => rootRouteImport,
} as any)
const Lesson5Route = Lesson5RouteImport.update({
  id: '/lesson5',
  path: '/lesson5',
  getParentRoute: () => rootRouteImport,
} as any)
const Lesson4Route = Lesson4RouteImport.update({
  id: '/lesson4',
  path: '/lesson4',
  getParentRoute: () => rootRouteImport,
} as any)
const Lesson3Route = Lesson3RouteImport.update({
  id: '/lesson3',
  path: '/lesson3',
  getParentRoute: () => rootRouteImport,
} as any)
const Lesson25Route = Lesson25RouteImport.update({
  id: '/lesson25',
  path: '/lesson25',
  getParentRoute: () => rootRouteImport,
} as any)
const Lesson24Route = Lesson24RouteImport.update({
  id: '/lesson24',
  path: '/lesson24',
  getParentRoute: () => rootRouteImport,
} as any)
const Lesson23Route = Lesson23RouteImport.update({
  id: '/lesson23',
  path: '/lesson23',
  getParentRoute: () => rootRouteImport,
} as any)
const Lesson22Route = Lesson22RouteImport.update({
  id: '/lesson22',
  path: '/lesson22',
  getParentRoute: () => rootRouteImport,
} as any)
const Lesson21Route = Lesson21RouteImport.update({
  id: '/lesson21',
  path: '/lesson21',
  getParentRoute: () => rootRouteImport,
} as any)
const Lesson20Route = Lesson20RouteImport.update({
  id: '/lesson20',
  path: '/lesson20',
  getParentRoute: () => rootRouteImport,
} as any)
const Lesson19Route = Lesson19RouteImport.update({
  id: '/lesson19',
  path: '/lesson19',
  getParentRoute: () => rootRouteImport,
} as any)
const Lesson11Route = Lesson11RouteImport.update({
  id: '/lesson11',
  path: '/lesson11',
  getParentRoute: () => rootRouteImport,
} as any)
const Lesson10Route = Lesson10RouteImport.update({
  id: '/lesson10',
  path: '/lesson10',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersIndexRoute = ChaptersIndexRouteImport.update({
  id: '/chapters/',
  path: '/chapters/',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonLessonIdRoute = LessonLessonIdRouteImport.update({
  id: '/lesson/$lessonId',
  path: '/lesson/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersChapterIdRoute = ChaptersChapterIdRouteImport.update({
  id: '/chapters/$chapterId',
  path: '/chapters/$chapterId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lesson10': typeof Lesson10Route
  '/lesson11': typeof Lesson11Route
  '/lesson19': typeof Lesson19Route
  '/lesson20': typeof Lesson20Route
  '/lesson21': typeof Lesson21Route
  '/lesson22': typeof Lesson22Route
  '/lesson23': typeof Lesson23Route
  '/lesson24': typeof Lesson24Route
  '/lesson25': typeof Lesson25Route
  '/lesson3': typeof Lesson3Route
  '/lesson4': typeof Lesson4Route
  '/lesson5': typeof Lesson5Route
  '/lesson6': typeof Lesson6Route
  '/lesson7': typeof Lesson7Route
  '/lesson8': typeof Lesson8Route
  '/lesson9': typeof Lesson9Route
  '/profile': typeof ProfileRoute
  '/chapters/$chapterId': typeof ChaptersChapterIdRoute
  '/lesson/$lessonId': typeof LessonLessonIdRoute
  '/chapters/': typeof ChaptersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lesson10': typeof Lesson10Route
  '/lesson11': typeof Lesson11Route
  '/lesson19': typeof Lesson19Route
  '/lesson20': typeof Lesson20Route
  '/lesson21': typeof Lesson21Route
  '/lesson22': typeof Lesson22Route
  '/lesson23': typeof Lesson23Route
  '/lesson24': typeof Lesson24Route
  '/lesson25': typeof Lesson25Route
  '/lesson3': typeof Lesson3Route
  '/lesson4': typeof Lesson4Route
  '/lesson5': typeof Lesson5Route
  '/lesson6': typeof Lesson6Route
  '/lesson7': typeof Lesson7Route
  '/lesson8': typeof Lesson8Route
  '/lesson9': typeof Lesson9Route
  '/profile': typeof ProfileRoute
  '/chapters/$chapterId': typeof ChaptersChapterIdRoute
  '/lesson/$lessonId': typeof LessonLessonIdRoute
  '/chapters': typeof ChaptersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lesson10': typeof Lesson10Route
  '/lesson11': typeof Lesson11Route
  '/lesson19': typeof Lesson19Route
  '/lesson20': typeof Lesson20Route
  '/lesson21': typeof Lesson21Route
  '/lesson22': typeof Lesson22Route
  '/lesson23': typeof Lesson23Route
  '/lesson24': typeof Lesson24Route
  '/lesson25': typeof Lesson25Route
  '/lesson3': typeof Lesson3Route
  '/lesson4': typeof Lesson4Route
  '/lesson5': typeof Lesson5Route
  '/lesson6': typeof Lesson6Route
  '/lesson7': typeof Lesson7Route
  '/lesson8': typeof Lesson8Route
  '/lesson9': typeof Lesson9Route
  '/profile': typeof ProfileRoute
  '/chapters/$chapterId': typeof ChaptersChapterIdRoute
  '/lesson/$lessonId': typeof LessonLessonIdRoute
  '/chapters/': typeof ChaptersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/lesson10'
    | '/lesson11'
    | '/lesson19'
    | '/lesson20'
    | '/lesson21'
    | '/lesson22'
    | '/lesson23'
    | '/lesson24'
    | '/lesson25'
    | '/lesson3'
    | '/lesson4'
    | '/lesson5'
    | '/lesson6'
    | '/lesson7'
    | '/lesson8'
    | '/lesson9'
    | '/profile'
    | '/chapters/$chapterId'
    | '/lesson/$lessonId'
    | '/chapters/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/lesson10'
    | '/lesson11'
    | '/lesson19'
    | '/lesson20'
    | '/lesson21'
    | '/lesson22'
    | '/lesson23'
    | '/lesson24'
    | '/lesson25'
    | '/lesson3'
    | '/lesson4'
    | '/lesson5'
    | '/lesson6'
    | '/lesson7'
    | '/lesson8'
    | '/lesson9'
    | '/profile'
    | '/chapters/$chapterId'
    | '/lesson/$lessonId'
    | '/chapters'
  id:
    | '__root__'
    | '/'
    | '/lesson10'
    | '/lesson11'
    | '/lesson19'
    | '/lesson20'
    | '/lesson21'
    | '/lesson22'
    | '/lesson23'
    | '/lesson24'
    | '/lesson25'
    | '/lesson3'
    | '/lesson4'
    | '/lesson5'
    | '/lesson6'
    | '/lesson7'
    | '/lesson8'
    | '/lesson9'
    | '/profile'
    | '/chapters/$chapterId'
    | '/lesson/$lessonId'
    | '/chapters/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Lesson10Route: typeof Lesson10Route
  Lesson11Route: typeof Lesson11Route
  Lesson19Route: typeof Lesson19Route
  Lesson20Route: typeof Lesson20Route
  Lesson21Route: typeof Lesson21Route
  Lesson22Route: typeof Lesson22Route
  Lesson23Route: typeof Lesson23Route
  Lesson24Route: typeof Lesson24Route
  Lesson25Route: typeof Lesson25Route
  Lesson3Route: typeof Lesson3Route
  Lesson4Route: typeof Lesson4Route
  Lesson5Route: typeof Lesson5Route
  Lesson6Route: typeof Lesson6Route
  Lesson7Route: typeof Lesson7Route
  Lesson8Route: typeof Lesson8Route
  Lesson9Route: typeof Lesson9Route
  ProfileRoute: typeof ProfileRoute
  ChaptersChapterIdRoute: typeof ChaptersChapterIdRoute
  LessonLessonIdRoute: typeof LessonLessonIdRoute
  ChaptersIndexRoute: typeof ChaptersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson9': {
      id: '/lesson9'
      path: '/lesson9'
      fullPath: '/lesson9'
      preLoaderRoute: typeof Lesson9RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson8': {
      id: '/lesson8'
      path: '/lesson8'
      fullPath: '/lesson8'
      preLoaderRoute: typeof Lesson8RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson7': {
      id: '/lesson7'
      path: '/lesson7'
      fullPath: '/lesson7'
      preLoaderRoute: typeof Lesson7RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson6': {
      id: '/lesson6'
      path: '/lesson6'
      fullPath: '/lesson6'
      preLoaderRoute: typeof Lesson6RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson5': {
      id: '/lesson5'
      path: '/lesson5'
      fullPath: '/lesson5'
      preLoaderRoute: typeof Lesson5RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson4': {
      id: '/lesson4'
      path: '/lesson4'
      fullPath: '/lesson4'
      preLoaderRoute: typeof Lesson4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson3': {
      id: '/lesson3'
      path: '/lesson3'
      fullPath: '/lesson3'
      preLoaderRoute: typeof Lesson3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson25': {
      id: '/lesson25'
      path: '/lesson25'
      fullPath: '/lesson25'
      preLoaderRoute: typeof Lesson25RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson24': {
      id: '/lesson24'
      path: '/lesson24'
      fullPath: '/lesson24'
      preLoaderRoute: typeof Lesson24RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson23': {
      id: '/lesson23'
      path: '/lesson23'
      fullPath: '/lesson23'
      preLoaderRoute: typeof Lesson23RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson22': {
      id: '/lesson22'
      path: '/lesson22'
      fullPath: '/lesson22'
      preLoaderRoute: typeof Lesson22RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson21': {
      id: '/lesson21'
      path: '/lesson21'
      fullPath: '/lesson21'
      preLoaderRoute: typeof Lesson21RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson20': {
      id: '/lesson20'
      path: '/lesson20'
      fullPath: '/lesson20'
      preLoaderRoute: typeof Lesson20RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson19': {
      id: '/lesson19'
      path: '/lesson19'
      fullPath: '/lesson19'
      preLoaderRoute: typeof Lesson19RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson11': {
      id: '/lesson11'
      path: '/lesson11'
      fullPath: '/lesson11'
      preLoaderRoute: typeof Lesson11RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson10': {
      id: '/lesson10'
      path: '/lesson10'
      fullPath: '/lesson10'
      preLoaderRoute: typeof Lesson10RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/': {
      id: '/chapters/'
      path: '/chapters'
      fullPath: '/chapters/'
      preLoaderRoute: typeof ChaptersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/$lessonId': {
      id: '/lesson/$lessonId'
      path: '/lesson/$lessonId'
      fullPath: '/lesson/$lessonId'
      preLoaderRoute: typeof LessonLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/$chapterId': {
      id: '/chapters/$chapterId'
      path: '/chapters/$chapterId'
      fullPath: '/chapters/$chapterId'
      preLoaderRoute: typeof ChaptersChapterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Lesson10Route: Lesson10Route,
  Lesson11Route: Lesson11Route,
  Lesson19Route: Lesson19Route,
  Lesson20Route: Lesson20Route,
  Lesson21Route: Lesson21Route,
  Lesson22Route: Lesson22Route,
  Lesson23Route: Lesson23Route,
  Lesson24Route: Lesson24Route,
  Lesson25Route: Lesson25Route,
  Lesson3Route: Lesson3Route,
  Lesson4Route: Lesson4Route,
  Lesson5Route: Lesson5Route,
  Lesson6Route: Lesson6Route,
  Lesson7Route: Lesson7Route,
  Lesson8Route: Lesson8Route,
  Lesson9Route: Lesson9Route,
  ProfileRoute: ProfileRoute,
  ChaptersChapterIdRoute: ChaptersChapterIdRoute,
  LessonLessonIdRoute: LessonLessonIdRoute,
  ChaptersIndexRoute: ChaptersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
